### PR TITLE
Fix channel map reshape

### LINKED ISSUE #951: Different charm versions displayed for ceph-mon
https://charmhub.io/ceph-mon

Both show as stable, `64` is the correct version.
Screen Shot 2021-04-26 at 3 24 52 PM

### PR DESCRIPTION
**Pull request by jkfran**
## Done
- Fix channel map reshape

## How to QA
- Visit: https://charmhub-io-1037.demos.haus/ceph-mon
- Check the version displayed in the dropdown is 66

## Issue / Card
Fixes #951

## Screenshots
image

### CODE REVIEW

**Comment by anthonydillon** [comment]
Your QA worked but when checking this charm: https://charmhub-io-1037.demos.haus/hello-kubecon I get "stable 11" when the latest version is 4.

**Comment by jkfran** [comment]
> Your QA worked but when checking this charm: https://charmhub-io-1037.demos.haus/hello-kubecon I get "stable 11" when the latest version is 4.

These changes were meant to fix the content inside the dropdown, which is good then because version 4 is the value shown.
I can see that the "stable 11" value in the dropdown is the revision number instead of the version number, should it be the version as well?

**Comment by jkfran** [comment]
> Your QA worked but when checking this charm: https://charmhub-io-1037.demos.haus/hello-kubecon I get "stable 11" when the latest version is 4.

Hey @anthonydillon , thank you for the review! It should be version 11 on both places for this charm now.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Pull request merged**
