### PR TITLE
Stop using platform, use base instead

### PR DESCRIPTION
**Pull request by tbille**
## Done
- Platforms are going to be dropped
- they are getting replaced with base
- This PR replaces every occurance of platform with base.

## How to QA
- `dotrun`
- http://0.0.0.0:8045/
- http://0.0.0.0:8045/containers-metallb-speaker
- Make sure all the filters are working

### CODE REVIEW

**Comment by solazio** [comment]
I think we should have the two things below consistent: both "platform" or both "base"
image

**Comment by tbille** [comment]
@solazio updated.

**Comment by solazio** [comment]
sorry @tbille, I also noticed this:
image

**Comment by tbille** [comment]
@solazio updated :smile:

**Review by solazio — APPROVED** [review]
Looks good :+1:. Thanks

**Pull request merged**
