### PR TITLE
Fix search filters

### PR DESCRIPTION
**Pull request by jkfran**
## Done

- Filtering is done in the backend now
- Also fixes https://github.com/canonical-web-and-design/charmhub.io/issues/540 , https://github.com/canonical-web-and-design/charmhub.io/issues/565 and https://github.com/canonical-web-and-design/charmhub.io/issues/567

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://localhost:8045
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Try to filter and search charms

## Issue / Card

Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/540

### CODE REVIEW

**Comment by tbille** [comment]
**Little bug:**

Go on homepage
select Database filter
Unselect database filter
Unselect featured

The page reloads with feature selected

**Comment by jkfran** [comment]
> **Little bug:**
> 
> Go on homepage
> select Database filter
> Unselect database filter
> Unselect featured
> 
> The page reloads with feature selected

Aaah the auto featured filter thing is killing me! I think I found a good solution now :)

**Comment by hatched** [comment]
QA Issue:

When you first load the page the count says `Showing 15 of 234 items` but if you check then uncheck featured it says `Showing 15 of 15 items`. 

It's also very slow, 5+s every time I click a checkbox. Refreshing the page every time a checkbox is checked is not a great experience.

**Comment by hatched** [comment]
Compared to the live version do you feel that the category interactions have improved? You can also compare to operatorhub to feel it out.

**Comment by tbille** [comment]
> When you first load the page the count says Showing 15 of 234 items but if you check then uncheck featured it says Showing 15 of 15 items.

This is a bug that we should fix.

> It's also very slow, 5+s every time I click a checkbox. Refreshing the page every time a checkbox is checked is not a great experience.

You are looking at uncached pages. This is normal behaviour at the moment.

> Compared to the live version do you feel that the category interactions have improved? You can also compare to operatorhub to feel it out.

We are aware of this. This has been a team decision to update this behaviour.

**Comment by steverydz** [comment]
Searching shows nothing even though there are results, e.g. https://charmhub-io-564.demos.haus/?q=apache

**Comment by solazio** [comment]
Is the green button on mobile needed if the filtering is done on the backend?
Also the filter and platform buttons don't look good on mobile.

image

**Comment by tbille** [comment]
We are going to block this issue for now. The bug is not release critical.
@jkfran keep this branch open so we can jump back on it when we are ready to work on it.

@hatched Just in case for release we are going to keep the frontend filtering, it does gives a better experience, and it's currently hard to prove that content-cache will solve our issues. 

We will have to figure out a new solution once the APIs for categories are ready. We have implemented something similar on snapcraft.io/store with some lazy loading of the categories.

> @solazio Is the green button on mobile needed if the filtering is done on the backend?

correct we might want to rethink that if we move this logic on the backend.

**Comment by jkfran** [comment]
I just want to give some more context:

- Doing it on the backend will make much more sense for now since we are expecting to not do any kind of filtering at all in our side and it will be done by the API.
- We knew it was going to be slower but also the current filtering speed can't be maintened in the future when the API implement the filtering.
- Currently it's a mess to work with some filters on backend and some in the frontend

In my opinion we should have another endpoint returning JSON data doing the filtering and frontend consuming it.

**Comment by tbille** [comment]
Closing
A lot has happened and change. This PR is not relevant anymore.

**Pull request closed without merging**
