### PR TITLE
fix: channel dropdown logic for multi-base channels

### PR DESCRIPTION
**Pull request by M7mdisk**
## Done

- Add "Base version" dropdown  in channels list
- Refactor the logic to show all revisions, not just latests ones.
- Show all bases associated with a channel regardless of which revision they're associated with.

## How to QA
- Go to any charm, the channel list menu should show the most recent releases for each channel, closely matching the output of `juju info charm-name`.
- When selecting an architecture, the output should the most recent channels supporting that architecture, matching `juju info charm-name --arch=arm64` for example.
- When selecting a base, the output should show the most recent channels with that base. matching  `juju info charm-name --base=ubuntu@20.04` for example.
- a combination of arch and base should work as well.
- Some good charms to test on (have many architectures and bases supported): `mysql-router`, `landscape-server`, `lxd`, `pgbouncer`.

Note: small caveat - The bases for each channel reflect all bases supported by the channel, not just the bases supported by the displayed revision

## Testing
- [ ] This PR has tests
- [x] No testing required (explain why): Fixes existing logic

## Issue / Card
Fixes [WD-10284](https://warthogs.atlassian.net/browse/WD-10284),  #1793 and #1741

[WD-10284]: https://warthogs.atlassian.net/browse/WD-10284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lukasSerelis** [comment]
Still some funkiness happening. For example, the [ceph charm](https://charmhub-io-1839.demos.haus/ceph-fs), if you select s390x as architecture, a bunch of base versions pop up, which is odd, we should have those exposed earlier, but might be `juju info` issue too.

**Comment by lukasSerelis** [comment]
Smaller detail, architecture dropdown order of elements seems to have changed their order. I'm not sure how it was sorted before, but would be best to sort it logically, like a-z.

**Comment by lukasSerelis** [comment]
A bigger detail - we're still not displaying all bases supported. [This charm](https://charmhub-io-1839.demos.haus/pgbouncer?channel=1/stable), doesn't show ubuntu@22.04 supported at all, but if you `juju info pgbouncer --base=ubuntu@22.04` you can see that it is supported 
image

Additionally, even the charm track list show the 22.04 version for some tracks, but doesn't surface it for filtering.

**Comment by lukasSerelis** [comment]
Another issue - might be out of scope for this, is that base versions aren't consistently displayed under platforms. 
image
assets/152963078/9b61d3b9-2fbb-47df-821c-9d0a41d289f4)
sometimes some versions are show, sometimes only 1

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Pull request merged**
