### PR TITLE
Update homepage loading animation

### LINKED ISSUE #784: Update homepage loading animation
On the left, in the current image:

- icon - rounded rectangle, while the incoming icons are predominantly circles
- gradient: transitions to pure white, which makes the shape break down. My suggestion is to use two light grays, e.g. `#f7f7f7` and `#e5e5e5`
- the gradient should ideally be over all shapes, not individual. I think that's feasible, let me know if you want me to find an example css implementation. The last image (the black gradient) illustrates how the top left to bottom-right gradient is relative to the top /bottom of the skeleton blocks as a whole, not individually:
- overall rectangle shape is truer to the font metrics. although not ideal. For an ideal one check out [this example](https://codepen.io/tylersticka/pen/PmRRqb?editors=1100) using an open source typeface named "redacted".

image

(The third image from the left is my actual proposal), unless we go with the redacted font, which will look slightly nicer.)

### PR DESCRIPTION
**Pull request by solazio**
## Done
- _Update homepage anymation._

## How to QA
- Visit the demo in your browser, link commented below
  - Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://localhost:8045/
  - If your demo doesn't work, read more about the [demoservice](https://discourse.ubuntu.com/t/demoservice/16862)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Un-hide the `<div class="l-flex__card-container u-hide" data-js="placeholder-container">` element on homepage
- Compare the animation with the design here #784 

## Issue / Card
Fixes #784 

## Screenshots
[if relevant, include a screenshot]

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Comment by solazio** [comment]
@lyubomir-popov maybe you can have a look at this as well

**Comment by lyubomir-popov** [comment]
The placeholder shapes do not match the dimensions and positioning of the card contents:

**Comment by solazio** [comment]
@lyubomir-popov I was not able to use your svg, but I got mine as close as possible. Please check again.

**Comment by lyubomir-popov** [comment]
@solazio looks great, thank you!

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
