### PR TITLE
Integration page

### LINKED ISSUE #432: Details: Build Integration page
Use mocked API

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Added integrate tab and integration charts

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://localhost:8045
- Click on an operator and go to <operator_name>/integrate
- Check that there is a list of operators
- Go to /activemq/integrate and click on an operator
- Check that there is an integration chart with one integration
- Go to /advanced-routing/integrate and click on an operator
- Check that there is an integration chart with two integrations
- Go to /ambassador/integrate and click on an operator
- Check that there is an integration chart with three integrations
- Go to /aodh/integrate and click on an operator
- Check that there is an integration chart with four integrations
- Go to /apache-flume-hdfs/integrate and click on an operator
- Check that there is an integration chart with five integrations
- Open any of the integration charts on mobile and check that it is a vertical chart with a carousel

**Note**: This is hard-coded data so there may be anomalies between charts

## Issue / Card

Fixes #432 

## Screenshots

integration_chart_desktop_one

integration_chart_desktop_two

integration_chart_desktop_3

integration_chart_desktop_four

integration_chart_desktop_5

integration_chart_mobile

### CODE REVIEW

**Comment by solazio** [comment]
I get this error when clicking on a operator in the list:
https://charmhub-io-465.demos.haus/activemq/integrate
Browser: Chromium 86.0.4240.111
```
attr.js:17 Error: <g> attribute transform: Trailing garbage, "translate(0, --1)".
(anonymous) @ attr.js:17
each @ each.js:5
attr @ attr.js:53
(anonymous) @ index.js:288
(anonymous) @ index.js:285
le @ index.js:451
setModalContent @ integrate:431
(anonymous) @ integrate:414
```

**Comment by solazio** [comment]
Is https://charmhub-io-465.demos.haus/ambassador/integrate not supposed to have 3 slides on mobile? It only has 2 on mobile.
image

**Comment by steverydz** [comment]
> Is https://charmhub-io-465.demos.haus/ambassador/integrate not supposed to have 3 slides on mobile? It only has 2 on mobile.

@solazio it's hardcoded so to get variation I'd have to hardcode every charm to get it to be different

**Review by tbille — APPROVED** [review]
LGTM

**Pull request merged**
