### PR TITLE
Move link to charm page from listing

### LINKED ISSUE #1148: listing page is missing a link to navigate back to the charm page
It would be handy if the listing page included a link for navigating back to the charm page.

At the moment there is only a link to "my charms and bundles" and the only way to go back to the charm page is by removing the "listing" suffix from the URL.

Screenshot from 2021-09-29 10-39-04

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Moved the link and save actions from bottom of listing page to top and updated the logic so it behaved more consistantly

## QA
- Go to https://charmhub-io-1197.demos.haus/landscape-keystone/listing
- Check that the `Updates to this information will appear immediately...` message is at the top of the page and that the buttons are disabled
- Check if you make changes to the form the buttons are enabled
- Check if you revert the form the buttons are disabled again

## Issue
Fixes #1148

### CODE REVIEW

**Comment by jkfran** [comment]
Hey Steve, looks good to me but I am going to invoke UXers at you 🪄 @AnnSoMuller @anasereijo

**Review by jkfran — APPROVED** [review]

**Comment by anasereijo** [comment]
Perfect 🥇

**Comment by anasereijo** [comment]
actually, this is -1, I'm sorry! forgot to check mobile:

the buttons have no padding on mobile view

Screenshot 2021-12-06 at 16 52 06

**Comment by steverydz** [comment]
@anasereijo thanks, fixed

**Comment by anasereijo** [comment]
LGTM!

**Pull request merged**
