### PR TITLE
Remove libraries introduction

### LINKED ISSUE #1332: Implement changes on libraries
https://github.com/canonical-web-and-design/charmhub.io/issues/1313#issuecomment-1105327105

### PR DESCRIPTION
**Pull request by jkfran**
## Done
- Remove libraries introduction

## How to QA
- Check a charm with libraries like https://charmhub-io-1341.demos.haus/nginx-ingress-integrator/libraries
- Check a charm without libraries https://charmhub-io-1341.demos.haus/graylog-k8s/libraries

## Issue / Card
Fixes #1332

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by anasereijo** [comment]
LGTM! thanks

**Comment by Lukewh** [comment]
LGTM too :+1:

**Comment by jnsgruk** [comment]
This is much better! Thank you all! :)

**Pull request merged**
