### PR TITLE
Add configuration tab

### PR DESCRIPTION
**Pull request by solazio**
## Done

Add configuration tab

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8045/charm#configuration
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Compare to [design](https://app.zeplin.io/project/5d3f1850b938ee0dc24c60c4/screen/5e2abd064f4c2353123c8366)
- **Note the links in the table of contents don't work**

## Issue / Card

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1264

### CODE REVIEW

**Comment by spencerbygraves** [comment]
@solazio is the contents nav using the vanilla list? the line height looks too tight.

**Comment by solazio** [comment]
> @solazio is the contents nav using the vanilla list? the line height looks too tight.

@spencerbygraves is using [table of contents component](https://vanillaframework.io/docs/patterns/table-of-contents) with no indentation and border on the left

**Comment by spencerbygraves** [comment]
@solazio ok, I see.

**Comment by Lukewh** [comment]
Ah - this is why I wanted to do JS in one go. Now we have this weird state where if you've got JS turned off, this works as expected. If you have JS turned on it doesn't, because JS is partially implemented - tabs only.
Now we're in this state I'm not sure what to suggest, I guess at this point this isn't production ready code, so it's fine to merge it - but we need to think about the non-JS vs JS soonish.

**Comment by solazio** [comment]
> Ah - this is why I wanted to do JS in one go. Now we have this weird state where if you've got JS turned off, this works as expected. If you have JS turned on it doesn't, because JS is partially implemented - tabs only.
> Now we're in this state I'm not sure what to suggest, I guess at this point this isn't production ready code, so it's fine to merge it - but we need to think about the non-JS vs JS soonish.

Yeah, I will add no more js for now.

**Pull request merged**
