### PR TITLE
Show featured charms by default

### LINKED ISSUE #460: Feature charms
We don't have a way to get the ops charms from the API but we know exaclyt the list of charms

This will be the list of charms ready:

```
Cortex
Grafana
Graylog
Filebeat
Prometheus
AlertManager
Elasticsearch
MongoDB
Cassandra
Mattermost
Wordpress
PostgreSQL
Discourse
MariaDB
Iscsi-Connector Charm
MetalLB
Kafka
OpenLDAP
```

### PR DESCRIPTION
**Pull request by tbille**
## Done

Featured charms by default on the homepage

## QA

- Check out this feature branch
- Run the site using the command `dotrun`
- http://localhost:8045
- Featured charms should be ticked by default
- Try to play around with the filters

## Issue / Card

Fixes #460 
Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/511
Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/501

### CODE REVIEW

**Comment by anthonydillon** [comment]
Are you sure we want to do this? I thought the aim was when people visited the website they saw lots of content?

**Comment by anthonydillon** [comment]
On small screens reset does not update the count

**Comment by tbille** [comment]
@anthonydillon I am updating the copydocs https://docs.google.com/document/d/1mps4SOa8_DA25fccYor3wxwV3ulQiD-uaocDHmaGmhw/edit?ts=5fa78d32#heading=h.hwa9exhwnuld

**Comment by tbille** [comment]
And to add more details: This is a random list of charms. Hopefully once I have a full list of featured charms we should have a more "full" page

**Comment by tbille** [comment]
There is still a bug in here:
- Remove category Featured
- Change platform

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
