### PR TITLE
Add hero typer to homepage

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Add hero typer to homepage

## How to QA
- Visit the demo in your browser, link commented below
- See that the words in the title auto type out
- Check small screens reverts to a single word

### CODE REVIEW

**Comment by spencerbygraves** [comment]
Thanks @anthonydillon. It's looking good but it feels a bit robotic because it types and deletes at the same pace, is there a way we can vary it a little?

Also, the orange on blue doesn't have a great contrast value, could we try white?

Thanks.

**Review by steverydz — APPROVED** [review]
I find it very distracting but it does what it's supposed to and the code looks good, so :+1:

**Comment by anthonydillon** [comment]
@spencerbygraves thanks. 
1. Updated the color to white. 
2. Added some randomness to the typing

**Comment by danielmutis** [comment]
@spencerbygraves @anthonydillon don't you think maybe the thing should be a bit faster? I reckon people won't stay there long to see all the words we want to put in there, they may even scroll before the first word is over.

**Comment by anthonydillon** [comment]
@danielmutis it was faster before but I want to give @spencerbygraves a chance to see it

**Comment by danielmutis** [comment]
Okay. @spencerbygraves is typing the right animation here? I have seen this done in a similar way to how Wayne did the animation on the Juju.is commands, which I think at least allows for the whole word to be loaded at once.

**Comment by spencerbygraves** [comment]
@danielmutis I'm not sure what animation you mean, the what is juju story?

I'm not tied to the typing effect, I assumed it was a request.

**Comment by spencerbygraves** [comment]
The speed is better on the [jaas homepage](https://jaas.ai/), if we go for typing

**Comment by spencerbygraves** [comment]
@anthonydillon thanks for the update, just a little quicker as before, or like the jaas homepage version and we're good.

Thanks.

**Comment by anthonydillon** [comment]
@spencerbygraves done.

**Comment by tbille** [comment]
@anthonydillon when there is a space, is it possible for you to directly jump to the next letter or add the space and the next letter together.
It looks like the writing lags when the space alone is added.

For example for `Bare metal`. Instead of adding the ` ` (between Bare and metal) could you directly add ` m`. This will avoid the weird jump.

**Comment by anthonydillon** [comment]
@tbille sure thing, good idea. Done.

**Review by tbille — APPROVED** [review]
Looks much better!

**Pull request merged**
