### PR TITLE
feat: unified search UI

### PR DESCRIPTION
**Pull request by M7mdisk**
## Done
- build UI for new unified search

## How to QA
- go to https://charmhub-io-1992.demos.haus/all-search
- try different search terms
- UI design still in a rough state, but functionality should work

## Testing
- [ ] This PR has tests
- [x] No testing required (explain why): search logic already covered by tests, this just adds a view

## Issue / Card
Fixes WD-14613

### CODE REVIEW

**Review by abbiesims — APPROVED** [review]
Looking good! :+1:

**Comment by AnnSoMuller** [comment]
He! Nice start!
[here](https://app.zeplin.io/project/63cfa77260818d13bbbf1cb1/screen/641054e97509973c8c45802f) is the "reference" on the UX side
as far as I have tested, the functionality works well.
- On the UX side, we are missing the "global search" in the main navigation to access the results (or that page)
- I like the idea that the section title links to the full list :)
However can we the add below something to show what we are showing ? like:
Screenshot 2024-09-03 at 15 29 23
On the design side I can also suggest some alignment with current search result pages like having the search results pages in < h5 > :)

**Comment by AnnSoMuller** [comment]
> * Global search nav will be added in another PR, it will be similar to the one on ubuntu.com
>   image
3. NOw I'm doing other esearch I found differencies when I search for "kubernetes"
I have no documentation results ans just 3 for the posts
Screenshot 2024-09-03 at 16 58 35
whereas I have more results when I click on the section titles
Screenshot 2024-09-03 at 16 58 21
YzJjMDhkNTg4OWY3MDY2NmZmZThlOWQzZGYxNmE2YWE4YWVhYjE4MTMxNzk4NTQ0NjkxOWMxOTQ1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GA1H1CCZMZd5qL6PG6snrMV2UmmA2anvXmsSJzUUdOU)
Screenshot 2024-09-03 at 17 01 21

**Comment by AnnSoMuller** [comment]
thanks for the explanations @M7mdisk 👍

**Comment by AnnSoMuller** [comment]
yes! last last change:
May you put the "showing the (...)" just below the title, above the results ?
Thanks

**Pull request merged**
