### PR TITLE
Embedded 404 page

### LINKED ISSUE #1274: Implement charm not found design for the 404 pages at /embedded endpoint
We could do this by either:
- Having a separate 404 page for these sub-resources
- Make the 404 page responsive

### PR DESCRIPTION
**Pull request by Lukewh**
## Done
- In the embedded view, capture exceptions and show an error page

## How to QA
- Visit the demo in your browser, link commented below
  - Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://localhost:8045/
  - If your demo doesn't work, read more about the [demoservice](https://discourse.ubuntu.com/t/demoservice/16862)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Visit https://charmhub-io-1329.demos.haus/hello/embedded and https://charmhub-io-1329.demos.haus/hello/embedded?store_design=true

## Issue / Card
Fixes #1274 

## Screenshots
In-store:
image
General embed:
image

### CODE REVIEW

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by anasereijo** [comment]
@spencerbygraves can you please have a quick look?

**Comment by spencerbygraves** [comment]
@Lukewh the store version above looks fine, but the icon in the general embed one is bigger than the Vanilla pattern. Could you match them please? Thanks.

**Comment by Lukewh** [comment]
@spencerbygraves updated:
image

**Pull request merged**
