### PR TITLE
Update settings page with the latest design

### PR DESCRIPTION
**Pull request by solazio**
## Done
- _Update settings page with the latest design._

## How to QA
- Run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://localhost:8045/[charm_name]/settings
- Compare to [design](https://app.zeplin.io/project/5fb68befd7ea8e4d263f3c26/screen/60410d521fc338109fa015cd)

## Issue / Card
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1893

## Screenshots
image

### CODE REVIEW

**Comment by tbille** [comment]
Sorry I think the design was missleading. Could you remove the collaborator section, we don't have any API yet for this.

**Comment by spencerbygraves** [comment]
Thanks @solazio I think the delete icons are supposed to show on hover only, is that correct @danielmutis?

**Comment by danielmutis** [comment]
@solazio @spencerbygraves yes, the trash icons are only on hover on the row.

**Comment by solazio** [comment]
@danielmutis @spencerbygraves I fixed the icons to appear only on hover.

**Review by jkfran — APPROVED** [review]
LGTM

**Pull request merged**
