### PR TITLE
Add husky and lint-staged

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Add husky and lint-staged

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8045
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Run it locally, make some changes and then commit. Note husky does the job and runs the linters

### CODE REVIEW

**Comment by hatched** [comment]
fwiw we've been removing husky from our other projects because we find that forcing people to lint every commit was not very welcome to everyone's workflow. Those who wanted it typically already have it as part of their editors.

**Comment by solazio** [comment]
thanks for letting us know @hatched. In that case @Lukewh shall I revert the change?

**Comment by Lukewh** [comment]
@hatched which projects have we removed husky from? Was there a conversation about it that I missed? I'm keen to keep it on charmhub and snapcraft - I think it's really valuable.

**Comment by anthonydillon** [comment]
I believe it was agreed its a per-project decision. In this case, I think it's useful as the websites use it.

**Pull request merged**
