### PR TITLE
Update branding color

### PR DESCRIPTION
**Pull request by tbille**
## Done

Update branding color
Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/572

## QA

- `dotrun`
- http://0.0.0.0:8045
- http://0.0.0.0:8045/overview

It should follow https://github.com/canonical-web-and-design/charmhub.io/issues/572#issuecomment-725465268

### CODE REVIEW

**Comment by clagom** [comment]
Nice - @spencerbygraves did you also open similar issues for juju.is and jaas.ai?

**Comment by spencerbygraves** [comment]
@tbille thanks, could you update a couple of things please...

- In the footer gradient, the colour should be #2C001E, not #511c39
- I can't see the header on the details pages in the demo, have they been updated to use the light grey?
- Can you update the light blue in this section on the overview page please:

image

**Comment by spencerbygraves** [comment]
>Nice - @spencerbygraves did you also open similar issues for juju.is and jaas.ai?

Not yet @clagom

**Review by anthonydillon — APPROVED** [review]
Code looks good :+1:

**Comment by spencerbygraves** [comment]
@tbille @anthonydillon >Can you update the light blue in this section on the overview page please:

Sorry, I meant the same grey as elsewhere - #F7F7F7

Thanks.

**Comment by anthonydillon** [comment]
@spencerbygraves ready again for a review. You can see a details page by going to the URL (/mysql)

**Comment by spencerbygraves** [comment]
@anthonydillon thanks, looks good 👍

**Pull request merged**
