### PR TITLE
Update discourse module

### PR DESCRIPTION
**Pull request by jkfran**
## Done

- Update discourse module

## QA

http://0.0.0.0:8045/mattermost/docs
Compare with URL map here: https://discourse.charmhub.io/t/mattermost-documentation-overview/3758

### CODE REVIEW

**Review by tbille — APPROVED** [review]
LGTM

**Comment by anthonydillon** [comment]
@jkfran the links to the first two navigation items are to discourse slugs `http://0.0.0.0:8045/t/mattermost-documentation-overview/3758`

**Comment by tbille** [comment]
@anthonydillon sure you are on the right branch, works well for me locally

**Comment by anthonydillon** [comment]
No I still get discourse links :man_shrugging:

**Comment by jkfran** [comment]
> No I still get discourse links man_shrugging

Weir, try with `dotrun clean`

**Pull request merged**
