### PR TITLE
Add summary and description to the charm overview page

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Add summary and description to the charm overview page

## QA

- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://localhost:8045/discourse
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- See there is a summary and a description at the top of the page

## Issue / Card

Fixes https://github.com/canonical-web-and-design/charmhub.io/issues/688

## Screenshots

image

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
I think we need to limit or address bad data before merging this. For example, https://charmhub-io-690.demos.haus/postgresql-k8s

**Comment by solazio** [comment]
> I think we need to limit or address bad data before merging this. For example, https://charmhub-io-690.demos.haus/postgresql-k8s

I agree that looks bad, but is the only one that I could find and is like that. We can limit the summary length to 90 (or whatever number makes sense) characters. What do you think @danielmutis ? Or can we update the charm metadata ourselves?

**Comment by danielmutis** [comment]
The summary should be limited to 100 characters as we calculated on Monday. For some reason in the cards for postgresql we show the description and not the summary?

**Comment by cristinadresch** [comment]
@danielmutis do we need a new design for this?

**Review by steverydz — APPROVED** [review]
LGTM :+1:

**Comment by danielmutis** [comment]
I think this is a good way of managing bad data, but we shouldn't merge this until they have had a chance to fix the new charms that have bad info here.

**Review by anthonydillon — APPROVED** [review]

**Pull request merged**
