### PR TITLE
Update tutorial link

### PR DESCRIPTION
**Pull request by tbille**
## Done

Update tutorial link

## QA

- `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8045/jenkins/docs
- Make sure link to tutorial is not 404

### CODE REVIEW

**Review by squidsoup — APPROVED** [review]
🥇

**Review by anthonydillon — COMMENTED** [review]
We should add a redirect too as people would have been using that link.

**Comment by tbille** [comment]
@anthonydillon already done ;)

**Comment by anthonydillon** [comment]
Ah in discourse, got ya. 👍

**Pull request merged**
